version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: crypto-wallet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crypto_wallet
      MYSQL_USER: crypto_user
      MYSQL_PASSWORD: crypto_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  api:
    build: .
    container_name: crypto-wallet-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:root@mysql:3306/crypto_wallet
      - SECRET_KEY=your-secret-key-change-this-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data: 